version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "12:00"  # Executa semanalmente aos sábados, às 12:00 no fuso horário do Brasil
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
