name: WakaTime
description: Run WakaTime command
inputs:
  WAKATIME_API_KEY:
    description: 'WakaTime API Key'
    required: true
runs:
  using: 'node14'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run WakaTime command
      env:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      run: |
        npx wakatime --api-key $WAKATIME_API_KEY --sync
