name: WakaTime Readme

on:
  schedule:
    - cron: "0 4 * * *" # Executa diariamente às 1h no horário de Brasília (UTC-3)
  workflow_dispatch:

env:
  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY}}
  GH_TOKEN: ${{ secrets.GH_TOKEN}}
  THEME: "default"

jobs:
  WakaTime-README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: MECR-0209/WakaTime-Readme@main
