name: Work Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Run MECR-0209/MECR-0209
        uses: MECR-0209/MECR-0209@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
