name: Waka Readme

on:
  schedule:
    # Roda à meia-noite no fuso horário de Brasília (UTC-3)
    - cron: '0 21 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: MECR-0209/MECR-0209@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
