name: WakaTime Readme

on:
  schedule:
    - cron: "0 4 * * *" # Executa diariamente às 1h no horário de Brasília (UTC-3)
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@2aab71918a9e3553309bda98e1cc570a07482d3c
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Update Wakapi stats
          BLOCKS: "⬜🟨🟩"
          TIME_RANGE: last_30_days
          SHOW_TIME: true
